"""
Professional PDF report generation for contract analysis
"""
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, Image
from reportlab.platypus.flowables import HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from datetime import datetime
from typing import Dict, List
import os


class ReportGenerator:
    """Generate professional PDF reports for contract analysis"""
    
    def __init__(self, output_path: str):
        """Initialize report generator"""
        self.output_path = output_path
        self.doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18,
        )
        self.styles = getSampleStyleSheet()
        self._create_custom_styles()
        self.story = []
    
    def _create_custom_styles(self):
        """Create custom paragraph styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a1a1a'),
            spaceAfter=30,
            alignment=TA_CENTER
        ))
        
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#2c5aa0'),
            spaceBefore=20,
            spaceAfter=12
        ))
        
        self.styles.add(ParagraphStyle(
            name='RiskHigh',
            parent=self.styles['BodyText'],
            textColor=colors.HexColor('#d32f2f'),
            fontSize=11
        ))
        
        self.styles.add(ParagraphStyle(
            name='RiskMedium',
            parent=self.styles['BodyText'],
            textColor=colors.HexColor('#f57c00'),
            fontSize=11
        ))
        
        self.styles.add(ParagraphStyle(
            name='RiskLow',
            parent=self.styles['BodyText'],
            textColor=colors.HexColor('#388e3c'),
            fontSize=11
        ))
    
    def add_cover_page(self, title: str, contract_type: str, date: str = None):
        """Add cover page to report"""
        if not date:
            date = datetime.now().strftime("%B %d, %Y")
        
        # Add vertical space
        self.story.append(Spacer(1, 2*inch))
        
        # Title
        title_para = Paragraph(title, self.styles['CustomTitle'])
        self.story.append(title_para)
        self.story.append(Spacer(1, 0.3*inch))
        
        # Contract type
        type_para = Paragraph(f"<b>Contract Type:</b> {contract_type}", 
                             self.styles['Heading3'])
        self.story.append(type_para)
        self.story.append(Spacer(1, 0.2*inch))
        
        # Date
        date_para = Paragraph(f"<b>Analysis Date:</b> {date}", 
                             self.styles['Normal'])
        self.story.append(date_para)
        self.story.append(Spacer(1, 1*inch))
        
        # Horizontal line
        self.story.append(HRFlowable(width="100%", thickness=2, 
                                     color=colors.HexColor('#2c5aa0')))
        
        # Generated by
        footer = Paragraph(
            "Generated by <b>Legal Fly Pro</b> - AI-Powered Contract Analysis",
            self.styles['Normal']
        )
        self.story.append(Spacer(1, 0.5*inch))
        self.story.append(footer)
        
        self.story.append(PageBreak())
    
    def add_executive_summary(self, risk_score: float, risk_level: str, 
                             total_findings: int, confidence: float = None):
        """Add executive summary section"""
        self.story.append(Paragraph("Executive Summary", self.styles['SectionHeader']))
        self.story.append(Spacer(1, 0.2*inch))
        
        # Risk score table
        data = [
            ['Metric', 'Value', 'Status'],
            ['Overall Risk Score', f'{risk_score}/10', risk_level],
            ['Total Risk Factors', str(total_findings), self._get_status(total_findings, 5, 10)],
        ]
        
        if confidence:
            data.append(['Classification Confidence', f'{confidence*100:.1f}%', 
                        'High' if confidence > 0.8 else 'Medium'])
        
        table = Table(data, colWidths=[2.5*inch, 1.5*inch, 1.5*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c5aa0')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        self.story.append(table)
        self.story.append(Spacer(1, 0.3*inch))
        
        # Risk level explanation
        explanations = {
            "Low": "This contract has minimal risk factors. Standard review recommended.",
            "Medium": "This contract contains moderate risks that should be addressed before signing.",
            "High": "⚠️ WARNING: This contract has significant risks requiring careful review and negotiation.",
            "Critical": "🚨 CRITICAL: This contract poses severe risks. Legal counsel strongly recommended."
        }
        
        explanation = Paragraph(
            f"<b>Assessment:</b> {explanations.get(risk_level, 'Review recommended.')}",
            self.styles['Normal']
        )
        self.story.append(explanation)
        self.story.append(Spacer(1, 0.3*inch))
    
    def add_risk_findings(self, findings: List[Dict]):
        """Add detailed risk findings section"""
        self.story.append(PageBreak())
        self.story.append(Paragraph("Risk Analysis Details", self.styles['SectionHeader']))
        self.story.append(Spacer(1, 0.2*inch))
        
        if not findings:
            para = Paragraph("✅ No significant risk factors identified.", 
                           self.styles['Normal'])
            self.story.append(para)
            return
        
        for i, finding in enumerate(findings, 1):
            # Risk title with severity
            severity = finding['severity']
            style = self.styles.get(f'Risk{severity}', self.styles['Normal'])
            
            title = Paragraph(
                f"<b>{i}. {finding['risk_type']} [{severity} Risk]</b>",
                style
            )
            self.story.append(title)
            self.story.append(Spacer(1, 0.1*inch))
            
            # Explanation
            explanation = Paragraph(
                f"<b>Issue:</b> {finding['explanation']}",
                self.styles['Normal']
            )
            self.story.append(explanation)
            self.story.append(Spacer(1, 0.05*inch))
            
            # Recommendation
            recommendation = Paragraph(
                f"<b>Recommendation:</b> {finding['recommendation']}",
                self.styles['Normal']
            )
            self.story.append(recommendation)
            
            # Context if available
            if finding.get('context'):
                context = Paragraph(
                    f"<i>Context: {finding['context'][:200]}...</i>",
                    self.styles['Italic']
                )
                self.story.append(Spacer(1, 0.05*inch))
                self.story.append(context)
            
            self.story.append(Spacer(1, 0.2*inch))
            self.story.append(HRFlowable(width="100%", thickness=0.5, 
                                        color=colors.lightgrey))
            self.story.append(Spacer(1, 0.2*inch))
    
    def add_clause_summary(self, clauses: List[Dict]):
        """Add clause analysis section"""
        self.story.append(PageBreak())
        self.story.append(Paragraph("Clause Analysis", self.styles['SectionHeader']))
        self.story.append(Spacer(1, 0.2*inch))
        
        if not clauses:
            return
        
        # Summary statistics
        total_clauses = len(clauses)
        important_clauses = [c for c in clauses if c.get('importance', 0) >= 0.7]
        
        summary_text = f"<b>Total Clauses Analyzed:</b> {total_clauses}<br/>"
        summary_text += f"<b>High-Importance Clauses:</b> {len(important_clauses)}"
        
        self.story.append(Paragraph(summary_text, self.styles['Normal']))
        self.story.append(Spacer(1, 0.3*inch))
        
        # Important clauses table
        if important_clauses:
            self.story.append(Paragraph("Key Clauses:", self.styles['Heading3']))
            self.story.append(Spacer(1, 0.1*inch))
            
            data = [['#', 'Clause Title', 'Type', 'Importance']]
            
            for i, clause in enumerate(important_clauses[:10], 1):
                clause_types = ', '.join(clause.get('clause_types', []))[:30]
                importance = f"{clause.get('importance', 0)*100:.0f}%"
                data.append([
                    str(i),
                    clause.get('title', 'Untitled')[:40],
                    clause_types,
                    importance
                ])
            
            table = Table(data, colWidths=[0.5*inch, 2.5*inch, 1.5*inch, 1*inch])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c5aa0')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
            ]))
            
            self.story.append(table)
    
    def add_recommendations(self, recommendations: List[str]):
        """Add recommendations section"""
        self.story.append(PageBreak())
        self.story.append(Paragraph("Recommendations", self.styles['SectionHeader']))
        self.story.append(Spacer(1, 0.2*inch))
        
        for i, rec in enumerate(recommendations, 1):
            rec_para = Paragraph(f"<b>{i}.</b> {rec}", self.styles['Normal'])
            self.story.append(rec_para)
            self.story.append(Spacer(1, 0.15*inch))
    
    def add_footer_note(self):
        """Add disclaimer footer"""
        self.story.append(PageBreak())
        self.story.append(Spacer(1, 2*inch))
        
        disclaimer = """
        <b>DISCLAIMER:</b><br/>
        This report is generated by AI-powered analysis and is intended for informational 
        purposes only. It does not constitute legal advice. Please consult with a qualified 
        attorney before making any legal decisions based on this analysis. The accuracy of 
        this analysis depends on the quality and completeness of the input document.
        """
        
        para = Paragraph(disclaimer, self.styles['Italic'])
        self.story.append(para)
    
    def generate(self) -> str:
        """Generate the PDF report"""
        self.doc.build(self.story)
        return self.output_path
    
    def _get_status(self, value: int, warning_threshold: int, 
                    critical_threshold: int) -> str:
        """Get status based on value and thresholds"""
        if value >= critical_threshold:
            return "Critical"
        elif value >= warning_threshold:
            return "Warning"
        else:
            return "Good"
